apiVersion: v1
kind: Service
metadata:
  name: {{ include "nanny.fullname" . }}
  labels:
    {{- include "nanny.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
  selector:
    {{- include "nanny.selectorLabels" . | nindent 4 }}
