# You can customise Nanny's name to be able to tell more of them apart.
name="Nanny"
addr="localhost:8080"
storage_dsn="file:nanny.sqlite" # SQLite data source name.

# Individual notifier settings.
[stderr]
enabled=true

[email]
enabled=false
from="nanny@myserver.com"
to=["someone@somewhere.com"]
subject="Nanny alert for %s"
subject_all_clear="Nanny all-clear for %s"
body="%s"
smtp_server="my.smtp.server"
smtp_port=587
smtp_user="someone@somewhere.com"
smtp_password=""

[sentry]
enabled=false
dsn=""

[twilio]
enabled=false
accountSid=""
authToken=""
appSid=""
from=""
to=""

[slack]
enabled=false
webhookURL=""

[webhook]
enabled=false
webhookURL="https://webhook.somewhere.com/webhook"
webhookURL_all_clear="https://webhook.somewhere.com/webhook"
webhookSecret=""
allowInsecureTLS=false

[xmpp]
enabled=false
to=["someone@xmpp.somewhere.com"]
xmpp_server="xmpp.somewhere.com"
xmpp_port=5222
xmpp_user="someone@xmpp.somewhere.com"
xmpp_password=""
xmpp_resource="Nanny"
xmpp_notls=false
