# Default values for nanny.

nanny:
  # Replica count of nanny (please be aware that nanny is currently not supporting any HA setup)
  replicaCount: 1

  # Enable debug logging of nanny:
  debug:
    enabled: false

  # Configure nanny instance name and listening address & port
  customConfig:
    name: "Nanny"
    addr: "0.0.0.0:8080"

  # Enable persistence for nannys sqlite DB:
  persistence:
    enabled: true
    existingClaim: ""
    # If defined, storageClassName: <storageClass>
    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined (the default) or set to null, no storageClassName spec is
    #   set, choosing the default provisioner.
    # storageClassName: "-"
    accessMode: ReadWriteOnce
    size: "1Gi"
    annotations: {}

  # Configure nanny image settings
  image:
    repository: lunemec/nanny
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.4.1"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  containerPort: 8080

  # Enable or disable the liveness probe
  livenessProbe:
    enabled: true

  # Enable or disable the readiness probe
  readinessProbe:
    enabled: true

  # Specify resource limits/requests for the nanny container
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: nanny.example.local
      paths: []
  tls: []
  #  - secretName: nanny-example-tls
  #    hosts:
  #      - nanny.example.local